# Generated by Django 4.2.4 on 2023-08-12 07:51

import apps.utils.functions
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timezone_str', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StoreReport',
            fields=[
                ('id', models.CharField(default=apps.utils.functions.custom_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('uptime_last_hour', models.IntegerField(blank=True, null=True)),
                ('uptime_last_day', models.IntegerField(blank=True, null=True)),
                ('update_last_week', models.IntegerField(blank=True, null=True)),
                ('downtime_last_hour', models.IntegerField(blank=True, null=True)),
                ('downtime_last_day', models.IntegerField(blank=True, null=True)),
                ('downtime_last_week', models.IntegerField(blank=True, null=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_report', to='home.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, max_length=15, null=True)),
                ('timestamp_utc', models.DateTimeField(blank=True, null=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_log', to='home.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayOfWeek', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('start_time_local', models.TimeField(blank=True, null=True)),
                ('end_time_local', models.TimeField(blank=True, null=True)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='store_hours', to='home.store')),
            ],
        ),
    ]
