# Generated by Django 4.2.4 on 2023-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_storereportheader_storereportitem_delete_storereport'),
    ]

    operations = [
        migrations.AddField(
            model_name='storereportheader',
            name='staus',
            field=models.CharField(choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=50),
        ),
    ]
