# Generated by Django 4.2.4 on 2023-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_storereportheader_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereportheader',
            name='created_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
