# Generated by Django 4.2.4 on 2023-08-14 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_storereportheader_created_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storereportheader',
            old_name='staus',
            new_name='status',
        ),
    ]
