# Generated by Django 4.2.4 on 2023-08-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_staus_storereportheader_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storehour',
            options={'ordering': ('store_id', 'dayOfWeek')},
        ),
        migrations.AlterModelOptions(
            name='storelog',
            options={'ordering': ('store_id', 'timestamp_utc')},
        ),
        migrations.AlterModelOptions(
            name='storereportheader',
            options={'ordering': ('-created_on',)},
        ),
        migrations.AlterModelOptions(
            name='storereportitem',
            options={'ordering': ('report_id',)},
        ),
        migrations.AddField(
            model_name='storereportheader',
            name='filepath',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
