# Generated by Django 4.2.4 on 2023-08-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_storehour_options_alter_storelog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereportheader',
            name='status',
            field=models.CharField(blank=True, choices=[('Running', 'Running'), ('Completed', 'Completed'), ('Failed', 'Failed')], default='Running', max_length=50, null=True),
        ),
    ]
