# Generated by Django 4.2.4 on 2023-08-14 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_storereportheader_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storereportitem',
            name='report_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_items', to='home.storereportheader'),
        ),
    ]
